### ISSUE TITLE
Tests fail on arm32v7 due to panic in library/core/src/option.rs

### ISSUE THREAD

**Issue by drauschenbach** [explodingcamera/tinywasm#26]
```sh
RUST_BACKTRACE=1 cargo test
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.28s
     Running unittests src/lib.rs (target/debug/deps/tinywasm-caf7dad3c6e70b52)

running 15 tests
test store::memory::memory_instance_tests::test_memory_custom_page_size_grow ... ok
test store::memory::memory_instance_tests::test_memory_copy_within_out_of_bounds ... ok
test store::memory::memory_instance_tests::test_memory_fill ... ok
test store::memory::memory_instance_tests::test_memory_fill_out_of_bounds ... ok
test store::memory::memory_instance_tests::test_memory_custom_page_size_out_of_bounds ... ok
test store::memory::memory_instance_tests::test_memory_copy_within ... ok
test store::memory::memory_instance_tests::test_memory_grow_out_of_bounds ... ok
test store::memory::memory_instance_tests::test_memory_store_out_of_bounds ... ok
test store::table::tests::test_get_wasm_val ... ok
test store::memory::memory_instance_tests::test_memory_store_and_load ... ok
test store::table::tests::test_table_init ... ok
test store::table::tests::test_set_and_get ... ok
test store::table::tests::test_table_instance_creation ... ok
test store::memory::memory_instance_tests::test_memory_grow ... ok
test store::memory::memory_instance_tests::test_memory_grow_max_pages ... ok

test result: ok. 15 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test-wasm-1.rs (target/debug/deps/test_wasm_1-fd1d60e6ef89fb31)
running group: address.wast
thread 'main' panicked at crates/tinywasm/tests/testsuite/run.rs:154:67:
failed to get test wast
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:264:5
   3: core::option::expect_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:2025:5
   4: core::option::Option<T>::expect
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:928:21
   5: test_wasm_1::testsuite::run::<impl test_wasm_1::testsuite::TestSuite>::run_spec_group::{{closure}}
             at ./tests/testsuite/run.rs:154:30
   6: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/iter/macros.rs:254:21
   7: test_wasm_1::testsuite::run::<impl test_wasm_1::testsuite::TestSuite>::run_spec_group
             at ./tests/testsuite/run.rs:151:9
   8: test_wasm_1::main
             at ./tests/test-wasm-1.rs:10:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: test failed, to rerun pass `-p tinywasm --test test-wasm-1`
```

**Comment by explodingcamera** [comment]
It looks like your missing the wasm testsuite, did you also clone the submodule? https://github.com/explodingcamera/tinywasm/blob/next/CONTRIBUTING.md#1-clone-the-repository

**Comment by drauschenbach** [comment]
That works. Thanks!
